# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/macc',
                'doc_host': 'https://niyazikemer.github.io',
                'git_url': 'https://github.com/niyazikemer/macc',
                'lib_path': 'macc'},
  'syms': {'macc.core': {'macc.core.foo': ('core.html#foo', 'macc/core.py')}}}
